### PR TITLE
Fr french translation

### PR DESCRIPTION
**Pull request by nyok92**
First pass of French Translation.
Any translation remarks welcomed

### CODE REVIEW

**Comment by JarvyJ** [comment]
Wow, this looks incredibly thorough! Thanks for the contribution. I'll merge it in in the next few days, feel free to make changes if needed and push them up.

**Comment by nyok92** [comment]
I don't know if volume_level numbers need to be translated in french words/ English words or we can let numbers.
PR ready to be merged

**Comment by JarvyJ** [comment]
Alright, let's give it a go! I'm planning for the next release this week, I'll try and get this merged along with some of the other open items.

Thanks again for the contribution!

**Comment by nyok92** [comment]
First bug found , I missed a comma : 

```
12/07/2022 10:07:38 INFO home_intent.rhasspy_api Trying to connect to Rhasspy at http://127.0.0.1:12101
12/07/2022 10:07:53 INFO root Using language: fr
12/07/2022 10:07:53 ERROR root invalid syntax (fr.py, line 12)
Traceback (most recent call last):
  File "/usr/src/app/home_intent/__main__.py", line 63, in main
    _load_integrations(settings, home_intent)
  File "/usr/src/app/home_intent/__main__.py", line 83, in _load_integrations
    loaded_builtin_components = _load_builtin_components(components, home_intent)
  File "/usr/src/app/home_intent/__main__.py", line 112, in _load_builtin_components
    integration.setup(home_intent)
  File "/usr/src/app/home_intent/components/timer/__init__.py", line 5, in setup
    timer = home_intent.import_module(__name__)
  File "/usr/src/app/home_intent/home_intent.py", line 136, in import_module
    module = import_module(f"{module_name}.{self.settings.home_intent.language}")
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/app/home_intent/components/timer/fr.py", line 12
    "troisquarts": "threequarters"
                 ^
SyntaxError: invalid syntax
```

**Pull request merged**
